name: Report a Crash
description: Sunshine crashed or generated a memory dump. Attach the crash bundle zip so we can investigate.
body:
  - type: markdown
    attributes:
      value: |
        ### How to export the crash bundle
        1. Open the Sunshine Web UI on the host machine.
        2. When the red crash banner appears on the Dashboard, click **Export Crash Bundle**  
           – or go to **Troubleshooting → Export Crash Bundle**.
        3. Attach the downloaded `sunshine_crashbundle-*.zip` below.

  - type: textarea
    id: summary
    attributes:
      label: Crash Summary
      description: Briefly describe what you were doing when Sunshine crashed.
      placeholder: Example – Sunshine crashed after launching Game XYZ while streaming in HDR.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce (if known)
      description: List any steps that reliably reproduce the crash.
      placeholder: |
        1. Start Sunshine
        2. Connect from Moonlight
        3. ...
    validations:
      required: false

  - type: textarea
    id: crash_bundle
    attributes:
      label: Crash Bundle Zip
      description: Drag and drop the exported `sunshine_crashbundle-*.zip` here.
      placeholder: Attach the crash bundle zip generated by Sunshine.
    validations:
      required: true

  - type: textarea
    id: extra_info
    attributes:
      label: Additional Details (optional)
      description: Anything else that could help (recent configuration changes, overclocks, etc.).
    validations:
      required: false

  - type: checkboxes
    id: confirmations
    attributes:
      label: Confirmation
      options:
        - label: I have exported the crash bundle using Sunshine's **Export Crash Bundle** action.
          required: true
        - label: I attached the `sunshine_crashbundle-*.zip` file to this issue.
          required: true
