encoder = nvenc_experimental
capture = kms
min_log_level = info
virtual_display_mode = shared
virtual_display_layout = exclusive
dd_config_revert_on_disconnect = enabled
dd_config_revert_delay = 0
origin_web_ui_allowed = pc
system_tray = disabled
session_history_enabled = disabled
frame_limiter_enable = false
file_apps = /var/lib/vibepollo-prelogin-static/apps.json
pkey = /var/lib/vibepollo-prelogin-static/credentials/cakey.pem
cert = /var/lib/vibepollo-prelogin-static/credentials/cacert.pem
file_state = /var/lib/vibepollo-prelogin/vibepollo/sunshine_state.json
vibeshine_file_state = /var/lib/vibepollo-prelogin/vibepollo/vibeshine_state.json
log_path = /var/lib/vibepollo-prelogin/vibepollo/logs/prelogin.log
